all:
	ghc --make etimingAttack.hs -fforce-recomp
	ghc --make itimingAttack.hs -fforce-recomp
	ghc --make Server.hs -fforce-recomp
	ghc --make simpleInternal.hs -fforce-recomp
	ghc --make termAttack2.hs -fforce-recomp
	ghc --make termAttack.hs -fforce-recomp
